@startuml
OtherObject -> AbstractAutowireCapableBeanFactory:createBean(beanName, mbd, Object[] args)
activate AbstractAutowireCapableBeanFactory
    AbstractAutowireCapableBeanFactory -> AbstractBeanFactory:resolveBeanClass(mbd,beanName,typesToMatch)
    note right:获得对应的Class对象
    activate AbstractBeanFactory
    return Class
'    deactivate   AbstractBeanFactory


    AbstractAutowireCapableBeanFactory -> AbstractBeanDefinition:prepareMethodOverrides()
    note right:对override属性进行标记及验证。
    activate AbstractBeanFactory
    return

    AbstractAutowireCapableBeanFactory -> AbstractAutowireCapableBeanFactory:resolveBeforeInstantiation(beanName, mbdToUse)
    note right:实例化前后的处理器，如果返回的bean不为null，则直接返回。
    activate AbstractBeanFactory
    return bean

    AbstractAutowireCapableBeanFactory -> AbstractAutowireCapableBeanFactory:doCreateBean(beanName,mbd,args)
    activate AbstractAutowireCapableBeanFactory
    return bean
return bean
@enduml